# Libraries

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('ggplot')

# Constants

In [2]:
DATA_PATH = '../DATA/news_125k-tokens-relevant.csv'

# Bespoke Functions

# Import data

In [3]:
df = pd.read_csv(DATA_PATH, index_col=0)
df

,title,body,category,votes,clicks,comments,text,clean_text,token_lemma,noun_adj_verb,token_lemma_relevant
0,"Muere Toni Batllori, autor de la tira diaria d...",Toni Batllori Obiols ha fallecido esta noche e...,Culture,144,1100,11,"Muere Toni Batllori, autor de la tira diaria d...",Muere Toni Batllori autor de la tira diaria de...,morir Toni Batllori autor tira diario Vanguard...,morir autor tirar diario fallecer noche domici...,morir Toni Batllori autor tirar diario Vanguar...
1,La anarquía explicada a los niños por José A. ...,"En 1931 el maestro José Antonio Emmanuel, y me...",Culture,196,1800,109,La anarquía explicada a los niños por José A. ...,La anarquía explicada a los niños por José A E...,anarquía explicado niño José Emmanuel 1931 mae...,anarquía explicado niño maestro publicar panfl...,anarquía explicado niño José Emmanuel maestro ...
2,"Rhianan Rudd, la adolescente a la que el MI5 a...","Rhianan Rudd, una adolescente de 14 años que v...",Latest,330,6100,77,"Rhianan Rudd, la adolescente a la que el MI5 a...",Rhianan Rudd la adolescente a la que el MI5 ac...,Rhianan Rudd adolescente MI5 acusar terrorismo...,adolescente acusar terrorismo acabar suicidar ...,Rhianan Rudd adolescente MI5 acusar terrorismo...
3,Piden por burofax al obispo de Cartagena que r...,"La catedral de Murcia, la iglesia de El Salvad...",Politics,410,881,54,Piden por burofax al obispo de Cartagena que r...,Piden por burofax al obispo de Cartagena que r...,pedir burofax obispo Cartagena retirar símbolo...,pedir burofax obispo retirar símbolo franquist...,pedir burofax obispo Cartagena retirar símbolo...
4,Érase una vez... (1950),Érase una vez... (1950) dirigida por Josep Esc...,Culture,114,100,9,Érase una vez... (1950) Érase una vez... (1950...,Érase una vez 1950 Érase una vez 1950 dirigida...,érar 1950 era él 1950 dirigido Josep Escobar Z...,érar 1950 1950 dirigido película entero hija c...,érar 1950 ser 1950 dirigido Josep Escobar Zipi...
...,...,...,...,...,...,...,...,...,...,...,...
123495,El juez descubre un traspaso de 150.000 euros ...,"El instructor del caso Noos, José Castro, acab...",Latest,1200,1200,46,El juez descubre un traspaso de 150.000 euros ...,El juez descubre un traspaso de 150000 euros d...,juez descubrir traspaso 150000 euros Aizóon In...,juez descubrir traspaso euros instructor caso ...,juez descubrir traspaso euros Aizóon Infanta i...
123496,La admiración de Isaac Asimov por Carl Sagan,La historia nos ha relatado muchas historias a...,Latest,498,500,130,La admiración de Isaac Asimov por Carl Sagan L...,La admiración de Isaac Asimov por Carl Sagan L...,admiración Isaac Asimov Carl Sagan historia re...,admiración historia relatar historia admiració...,admiración Isaac Asimov Carl Sagan historia re...
123497,El hombre con 59.000 libros... en su casa (ENG),"En la década de 1920, Lawrence L. Thomas, un d...",Latest,270,9400,68,El hombre con 59.000 libros... en su casa (ENG...,El hombre con 59000 libros en su casa ENG En l...,hombre 59000 libro casa ENG década 1920 Lawren...,hombre libro casa década hijo deseado nacido r...,hombre libro casa ENG década Lawrence L Thomas...
123498,"La BBC habla de ""bronca por el peaje solar"" en...",La TV pública británica resalta las críticas y...,Latest,1200,2500,30,"La BBC habla de ""bronca por el peaje solar"" en...",La BBC habla de bronca por el peaje solar en E...,BBC bronca peaje solar España TV público britá...,peaje solar público británico resaltar crítica...,BBC bronca peaje solar España TV público britá...
123499,Multa millonaria a Tesla por exagerar autonomía,"La Comisión de Comercio Justo explicó que, seg...",Latest,405,1700,54,Multa millonaria a Tesla por exagerar autonomí...,Multa millonaria a Tesla por exagerar autonomí...,multa millonario Tesla exagerar autonomía Comi...,multa millonario exagerar autonomía mentir vel...,multa millonario Tesla exagerar autonomía Comi...

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 123500 entries, 0 to 123499
Data columns (total 11 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   title                 123500 non-null  object
 1   body                  123500 non-null  object
 2   category              123500 non-null  object
 3   votes                 123500 non-null  int64
 4   clicks                123500 non-null  int64
 5   comments              123500 non-null  int64
 6   text                  123500 non-null  object
 7   clean_text            123500 non-null  object
 8   token_lemma           123500 non-null  object
 9   noun_adj_verb         123414 non-null  object
 10  token_lemma_relevant  123500 non-null  object
dtypes: int64(3), object(8)
memory usage: 11.3+ MB

### Import Topic

In [5]:
df_topic = pd.read_csv('../DATA/news_125k-tokens-relevant-with_topic.csv', index_col=0)
df_topic

,title,body,category,votes,clicks,comments,text,clean_text,token_lemma,noun_adj_verb,token_lemma_relevant,tokens_for_topics,topic,topic_name
0,"Muere Toni Batllori, autor de la tira diaria d...",Toni Batllori Obiols ha fallecido esta noche e...,Culture,144,1100,11,"Muere Toni Batllori, autor de la tira diaria d...",Muere Toni Batllori autor de la tira diaria de...,morir Toni Batllori autor tira diario Vanguard...,morir autor tirar diario fallecer noche domici...,morir Toni Batllori autor tirar diario Vanguar...,"['morir', 'toni', 'batllori', 'autor', 'tira',...",0,entertainment
1,La anarquía explicada a los niños por José A. ...,"En 1931 el maestro José Antonio Emmanuel, y me...",Culture,196,1800,109,La anarquía explicada a los niños por José A. ...,La anarquía explicada a los niños por José A E...,anarquía explicado niño José Emmanuel 1931 mae...,anarquía explicado niño maestro publicar panfl...,anarquía explicado niño José Emmanuel maestro ...,"['anarquía', 'explicado', 'niño', 'josé', 'emm...",0,entertainment
2,"Rhianan Rudd, la adolescente a la que el MI5 a...","Rhianan Rudd, una adolescente de 14 años que v...",Latest,330,6100,77,"Rhianan Rudd, la adolescente a la que el MI5 a...",Rhianan Rudd la adolescente a la que el MI5 ac...,Rhianan Rudd adolescente MI5 acusar terrorismo...,adolescente acusar terrorismo acabar suicidar ...,Rhianan Rudd adolescente MI5 acusar terrorismo...,"['rhianan', 'rudd', 'adolescente', 'acusar', '...",1,labor
3,Piden por burofax al obispo de Cartagena que r...,"La catedral de Murcia, la iglesia de El Salvad...",Politics,410,881,54,Piden por burofax al obispo de Cartagena que r...,Piden por burofax al obispo de Cartagena que r...,pedir burofax obispo Cartagena retirar símbolo...,pedir burofax obispo retirar símbolo franquist...,pedir burofax obispo Cartagena retirar símbolo...,"['pedir', 'burofax', 'obispo', 'cartagena', 'r...",1,labor
4,Érase una vez... (1950),Érase una vez... (1950) dirigida por Josep Esc...,Culture,114,100,9,Érase una vez... (1950) Érase una vez... (1950...,Érase una vez 1950 Érase una vez 1950 dirigida...,érar 1950 era él 1950 dirigido Josep Escobar Z...,érar 1950 1950 dirigido película entero hija c...,érar 1950 ser 1950 dirigido Josep Escobar Zipi...,"['érase', 'érase', 'dirigido', 'josep', 'escob...",0,entertainment
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123495,El juez descubre un traspaso de 150.000 euros ...,"El instructor del caso Noos, José Castro, acab...",Latest,1200,1200,46,El juez descubre un traspaso de 150.000 euros ...,El juez descubre un traspaso de 150000 euros d...,juez descubrir traspaso 150000 euros Aizóon In...,juez descubrir traspaso euros instructor caso ...,juez descubrir traspaso euros Aizóon Infanta i...,"['juez', 'descubrir', 'traspaso', 'euros', 'ai...",4,spanish monarchy
123496,La admiración de Isaac Asimov por Carl Sagan,La historia nos ha relatado muchas historias a...,Latest,498,500,130,La admiración de Isaac Asimov por Carl Sagan L...,La admiración de Isaac Asimov por Carl Sagan L...,admiración Isaac Asimov Carl Sagan historia re...,admiración historia relatar historia admiració...,admiración Isaac Asimov Carl Sagan historia re...,"['admiración', 'isaac', 'asimov', 'carl', 'sag...",0,entertainment
123497,El hombre con 59.000 libros... en su casa (ENG),"En la década de 1920, Lawrence L. Thomas, un d...",Latest,270,9400,68,El hombre con 59.000 libros... en su casa (ENG...,El hombre con 59000 libros en su casa ENG En l...,hombre 59000 libro casa ENG década 1920 Lawren...,hombre libro casa década hijo deseado nacido r...,hombre libro casa ENG década Lawrence L Thomas...,"['hombre', 'libro', 'casa', 'eng', 'década', '...",0,entertainment
123498,"La BBC habla de ""bronca por el peaje solar"" en...",La TV pública británica resalta las críticas y...,Latest,1200,2500,30,"La BBC habla de ""bronca por el peaje solar"" en...",La BBC habla de bronca por el peaje solar en E...,BBC bronca peaje solar España TV público britá...,peaje solar público británico resaltar crítica...,BBC bronca peaje solar España TV público britá...,"['bbc', 'bronca', 'peaje', 'solar', 'españa', ...",0,entertainment
123499,Multa millonaria a Tesla por exagerar autonomía,"La Comisión de Comercio Justo explicó que, seg...",Latest,405,1700,54,Multa millonaria a Tesla por exagerar autonomí...,Multa millonaria a Tesla por exagerar autonomí...,multa millonario Tesla exagerar autonomía Comi...,multa millonario exagerar autonomía mentir vel...,multa millonario Tesla exagerar autonomía Comi...,"['multa', 'millonario', 'tesla', 'exagerar', '...",2,environment

In [6]:
df_topic.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 123500 entries, 0 to 123499
Data columns (total 14 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   title                 123500 non-null  object
 1   body                  123500 non-null  object
 2   category              123500 non-null  object
 3   votes                 123500 non-null  int64
 4   clicks                123500 non-null  int64
 5   comments              123500 non-null  int64
 6   text                  123500 non-null  object
 7   clean_text            123500 non-null  object
 8   token_lemma           123500 non-null  object
 9   noun_adj_verb         123414 non-null  object
 10  token_lemma_relevant  123500 non-null  object
 11  tokens_for_topics     123500 non-null  object
 12  topic                 123500 non-null  int64
 13  topic_name            123500 non-null  object
dtypes: int64(4), object(10)
memory usage: 14.1+ MB

In [7]:
df_topic.isna().sum()

title                    0
body                     0
category                 0
votes                    0
clicks                   0
comments                 0
text                     0
clean_text               0
token_lemma              0
noun_adj_verb           86
token_lemma_relevant     0
tokens_for_topics        0
topic                    0
topic_name               0
dtype: int64

### Import Polarity

In [8]:
df_polarity = pd.read_csv('../DATA/news_125k-tokens-relevant-with_polarity.csv', index_col=0)
df_polarity

,title,body,category,votes,clicks,comments,text,clean_text,token_lemma,noun_adj_verb,token_lemma_relevant,polarity,polarity_score
0,"Muere Toni Batllori, autor de la tira diaria d...",Toni Batllori Obiols ha fallecido esta noche e...,Culture,144,1100,11,"Muere Toni Batllori, autor de la tira diaria d...",Muere Toni Batllori autor de la tira diaria de...,morir Toni Batllori autor tira diario Vanguard...,morir autor tirar diario fallecer noche domici...,morir Toni Batllori autor tirar diario Vanguar...,5 stars,0.24
1,La anarquía explicada a los niños por José A. ...,"En 1931 el maestro José Antonio Emmanuel, y me...",Culture,196,1800,109,La anarquía explicada a los niños por José A. ...,La anarquía explicada a los niños por José A E...,anarquía explicado niño José Emmanuel 1931 mae...,anarquía explicado niño maestro publicar panfl...,anarquía explicado niño José Emmanuel maestro ...,4 stars,0.31
2,"Rhianan Rudd, la adolescente a la que el MI5 a...","Rhianan Rudd, una adolescente de 14 años que v...",Latest,330,6100,77,"Rhianan Rudd, la adolescente a la que el MI5 a...",Rhianan Rudd la adolescente a la que el MI5 ac...,Rhianan Rudd adolescente MI5 acusar terrorismo...,adolescente acusar terrorismo acabar suicidar ...,Rhianan Rudd adolescente MI5 acusar terrorismo...,3 stars,0.23
3,Piden por burofax al obispo de Cartagena que r...,"La catedral de Murcia, la iglesia de El Salvad...",Politics,410,881,54,Piden por burofax al obispo de Cartagena que r...,Piden por burofax al obispo de Cartagena que r...,pedir burofax obispo Cartagena retirar símbolo...,pedir burofax obispo retirar símbolo franquist...,pedir burofax obispo Cartagena retirar símbolo...,1 star,0.46
4,Érase una vez... (1950),Érase una vez... (1950) dirigida por Josep Esc...,Culture,114,100,9,Érase una vez... (1950) Érase una vez... (1950...,Érase una vez 1950 Érase una vez 1950 dirigida...,érar 1950 era él 1950 dirigido Josep Escobar Z...,érar 1950 1950 dirigido película entero hija c...,érar 1950 ser 1950 dirigido Josep Escobar Zipi...,4 stars,0.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...
123495,El juez descubre un traspaso de 150.000 euros ...,"El instructor del caso Noos, José Castro, acab...",Latest,1200,1200,46,El juez descubre un traspaso de 150.000 euros ...,El juez descubre un traspaso de 150000 euros d...,juez descubrir traspaso 150000 euros Aizóon In...,juez descubrir traspaso euros instructor caso ...,juez descubrir traspaso euros Aizóon Infanta i...,1 star,0.28
123496,La admiración de Isaac Asimov por Carl Sagan,La historia nos ha relatado muchas historias a...,Latest,498,500,130,La admiración de Isaac Asimov por Carl Sagan L...,La admiración de Isaac Asimov por Carl Sagan L...,admiración Isaac Asimov Carl Sagan historia re...,admiración historia relatar historia admiració...,admiración Isaac Asimov Carl Sagan historia re...,4 stars,0.42
123497,El hombre con 59.000 libros... en su casa (ENG),"En la década de 1920, Lawrence L. Thomas, un d...",Latest,270,9400,68,El hombre con 59.000 libros... en su casa (ENG...,El hombre con 59000 libros en su casa ENG En l...,hombre 59000 libro casa ENG década 1920 Lawren...,hombre libro casa década hijo deseado nacido r...,hombre libro casa ENG década Lawrence L Thomas...,5 stars,0.32
123498,"La BBC habla de ""bronca por el peaje solar"" en...",La TV pública británica resalta las críticas y...,Latest,1200,2500,30,"La BBC habla de ""bronca por el peaje solar"" en...",La BBC habla de bronca por el peaje solar en E...,BBC bronca peaje solar España TV público britá...,peaje solar público británico resaltar crítica...,BBC bronca peaje solar España TV público britá...,1 star,0.64
123499,Multa millonaria a Tesla por exagerar autonomía,"La Comisión de Comercio Justo explicó que, seg...",Latest,405,1700,54,Multa millonaria a Tesla por exagerar autonomí...,Multa millonaria a Tesla por exagerar autonomí...,multa millonario Tesla exagerar autonomía Comi...,multa millonario exagerar autonomía mentir vel...,multa millonario Tesla exagerar autonomía Comi...,1 star,0.69

In [9]:
df_polarity.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 123500 entries, 0 to 123499
Data columns (total 13 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   title                 123500 non-null  object
 1   body                  123500 non-null  object
 2   category              123500 non-null  object
 3   votes                 123500 non-null  int64
 4   clicks                123500 non-null  int64
 5   comments              123500 non-null  int64
 6   text                  123500 non-null  object
 7   clean_text            123500 non-null  object
 8   token_lemma           123500 non-null  object
 9   noun_adj_verb         123414 non-null  object
 10  token_lemma_relevant  123500 non-null  object
 11  polarity              123500 non-null  object
 12  polarity_score        123500 non-null  float64
dtypes: float64(1), int64(3), object(9)
memory usage: 13.2+ MB

In [10]:
df_polarity.isna().sum()

title                    0
body                     0
category                 0
votes                    0
clicks                   0
comments                 0
text                     0
clean_text               0
token_lemma              0
noun_adj_verb           86
token_lemma_relevant     0
polarity                 0
polarity_score           0
dtype: int64

### Import Score

In [11]:
df_score = pd.read_csv('../DATA/news_125k-with_score.csv', index_col=0)
df_score

,title,body,category,votes,clicks,comments,text,clean_text,token_lemma,noun_adj_verb,token_lemma_relevant,clicks_log,votes_log,comments_log,score,rank,status,score_name
0,"Muere Toni Batllori, autor de la tira diaria d...",Toni Batllori Obiols ha fallecido esta noche e...,Culture,144,1100,11,"Muere Toni Batllori, autor de la tira diaria d...",Muere Toni Batllori autor de la tira diaria de...,morir Toni Batllori autor tira diario Vanguard...,morir autor tirar diario fallecer noche domici...,morir Toni Batllori autor tirar diario Vanguar...,7.003065,4.969813,2.397895,4.130580,121598.0,Below,C
1,La anarquía explicada a los niños por José A. ...,"En 1931 el maestro José Antonio Emmanuel, y me...",Culture,196,1800,109,La anarquía explicada a los niños por José A. ...,La anarquía explicada a los niños por José A E...,anarquía explicado niño José Emmanuel 1931 mae...,anarquía explicado niño maestro publicar panfl...,anarquía explicado niño José Emmanuel maestro ...,7.495542,5.278115,4.691348,5.459279,69581.0,Below,B
2,"Rhianan Rudd, la adolescente a la que el MI5 a...","Rhianan Rudd, una adolescente de 14 años que v...",Latest,330,6100,77,"Rhianan Rudd, la adolescente a la que el MI5 a...",Rhianan Rudd la adolescente a la que el MI5 ac...,Rhianan Rudd adolescente MI5 acusar terrorismo...,adolescente acusar terrorismo acabar suicidar ...,Rhianan Rudd adolescente MI5 acusar terrorismo...,8.716044,5.799093,4.343805,5.699596,48443.0,Above,B
3,Piden por burofax al obispo de Cartagena que r...,"La catedral de Murcia, la iglesia de El Salvad...",Politics,410,881,54,Piden por burofax al obispo de Cartagena que r...,Piden por burofax al obispo de Cartagena que r...,pedir burofax obispo Cartagena retirar símbolo...,pedir burofax obispo retirar símbolo franquist...,pedir burofax obispo Cartagena retirar símbolo...,6.781058,6.016157,3.988984,5.176667,91042.0,Below,C
4,Érase una vez... (1950),Érase una vez... (1950) dirigida por Josep Esc...,Culture,114,100,9,Érase una vez... (1950) Érase una vez... (1950...,Érase una vez 1950 Érase una vez 1950 dirigida...,érar 1950 era él 1950 dirigido Josep Escobar Z...,érar 1950 1950 dirigido película entero hija c...,érar 1950 ser 1950 dirigido Josep Escobar Zipi...,4.605170,4.736198,2.197225,3.453340,123376.0,Below,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123495,El juez descubre un traspaso de 150.000 euros ...,"El instructor del caso Noos, José Castro, acab...",Latest,1200,1200,46,El juez descubre un traspaso de 150.000 euros ...,El juez descubre un traspaso de 150000 euros d...,juez descubrir traspaso 150000 euros Aizóon In...,juez descubrir traspaso euros instructor caso ...,juez descubrir traspaso euros Aizóon Infanta i...,7.090077,7.090077,3.828641,5.477949,67941.0,Below,B
123496,La admiración de Isaac Asimov por Carl Sagan,La historia nos ha relatado muchas historias a...,Latest,498,500,130,La admiración de Isaac Asimov por Carl Sagan L...,La admiración de Isaac Asimov por Carl Sagan L...,admiración Isaac Asimov Carl Sagan historia re...,admiración historia relatar historia admiració...,admiración Isaac Asimov Carl Sagan historia re...,6.214608,6.210600,4.867534,5.547574,61846.0,Above,B
123497,El hombre con 59.000 libros... en su casa (ENG),"En la década de 1920, Lawrence L. Thomas, un d...",Latest,270,9400,68,El hombre con 59.000 libros... en su casa (ENG...,El hombre con 59000 libros en su casa ENG En l...,hombre 59000 libro casa ENG década 1920 Lawren...,hombre libro casa década hijo deseado nacido r...,hombre libro casa ENG década Lawrence L Thomas...,9.148465,5.598422,4.219508,5.671209,50852.0,Above,B
123498,"La BBC habla de ""bronca por el peaje solar"" en...",La TV pública británica resalta las críticas y...,Latest,1200,2500,30,"La BBC habla de ""bronca por el peaje solar"" en...",La BBC habla de bronca por el peaje solar en E...,BBC bronca peaje solar España TV público britá...,peaje solar público británico resaltar crítica...,BBC bronca peaje solar España TV público britá...,7.824046,7.090077,3.401197,5.422632,72639.0,Below,B
123499,Multa millonaria a Tesla por exagerar autonomía,"La Comisión de Comercio Justo explicó que, seg...",Latest,405,1700,54,Multa millonaria a Tesla por exagerar autonomí...,Multa millonaria a Tesla por exagerar autonomí...,multa millonario Tesla exagerar autonomía Comi...,multa millonario exagerar autonomía mentir vel...,multa millonario Tesla exagerar autonomía Comi...,7.438384,6.003887,3.988984,5.312751,81398.0,Below,B

In [12]:
df_score.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 123500 entries, 0 to 123499
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   title                 123500 non-null  object
 1   body                  123500 non-null  object
 2   category              123500 non-null  object
 3   votes                 123500 non-null  int64
 4   clicks                123500 non-null  int64
 5   comments              123500 non-null  int64
 6   text                  123500 non-null  object
 7   clean_text            123500 non-null  object
 8   token_lemma           123500 non-null  object
 9   noun_adj_verb         123414 non-null  object
 10  token_lemma_relevant  123500 non-null  object
 11  clicks_log            123500 non-null  float64
 12  votes_log             123500 non-null  float64
 13  comments_log          123500 non-null  float64
 14  score                 123500 non-null  float64
 15  rank                  123500 non-null  float64
 16  status                123500 non-null  object
 17  score_name            123500 non-null  object
dtypes: float64(5), int64(3), object(10)
memory usage: 17.9+ MB

In [13]:
df_score.iloc[1341]

title                   Detenido un hombre por violar a una niña de 13...
body                    La Guardia Civil ha detenido en Felanitx a un ...
category                                                           Latest
votes                                                                 303
clicks                                                               2200
comments                                                               92
text                    Detenido un hombre por violar a una niña de 13...
clean_text              Detenido un hombre por violar a una niña de 13...
token_lemma             detener hombre violar niña 13 año Felanitx Gua...
noun_adj_verb           detener hombre violar niña año detener hombre ...
token_lemma_relevant    detener hombre violar niña año Felanitx Guardi...
clicks_log                                                       7.696213
votes_log                                                        5.713733
comments_log                                                     4.521789
score                                                            5.545832
rank                                                              61994.0
status                                                              Above
score_name                                                              B
Name: 1341, dtype: object

### Add polarity, topic and score columns to df

In [14]:
df['topic'] = df_topic['topic']
df['topic_name'] = df_topic['topic_name']

In [15]:
df['polarity'] = df_polarity['polarity']
df['polarity_score'] = df_polarity['polarity_score']

In [16]:
df['score'] = df_score['score']
df['score_name'] = df_score['score_name']
df['rank'] = df_score['rank']
df['status'] = df_score['status']

In [17]:
df

,title,body,category,votes,clicks,comments,text,clean_text,token_lemma,noun_adj_verb,token_lemma_relevant,topic,topic_name,polarity,polarity_score,score,score_name,rank,status
0,"Muere Toni Batllori, autor de la tira diaria d...",Toni Batllori Obiols ha fallecido esta noche e...,Culture,144,1100,11,"Muere Toni Batllori, autor de la tira diaria d...",Muere Toni Batllori autor de la tira diaria de...,morir Toni Batllori autor tira diario Vanguard...,morir autor tirar diario fallecer noche domici...,morir Toni Batllori autor tirar diario Vanguar...,0,entertainment,5 stars,0.24,4.130580,C,121598.0,Below
1,La anarquía explicada a los niños por José A. ...,"En 1931 el maestro José Antonio Emmanuel, y me...",Culture,196,1800,109,La anarquía explicada a los niños por José A. ...,La anarquía explicada a los niños por José A E...,anarquía explicado niño José Emmanuel 1931 mae...,anarquía explicado niño maestro publicar panfl...,anarquía explicado niño José Emmanuel maestro ...,0,entertainment,4 stars,0.31,5.459279,B,69581.0,Below
2,"Rhianan Rudd, la adolescente a la que el MI5 a...","Rhianan Rudd, una adolescente de 14 años que v...",Latest,330,6100,77,"Rhianan Rudd, la adolescente a la que el MI5 a...",Rhianan Rudd la adolescente a la que el MI5 ac...,Rhianan Rudd adolescente MI5 acusar terrorismo...,adolescente acusar terrorismo acabar suicidar ...,Rhianan Rudd adolescente MI5 acusar terrorismo...,1,labor,3 stars,0.23,5.699596,B,48443.0,Above
3,Piden por burofax al obispo de Cartagena que r...,"La catedral de Murcia, la iglesia de El Salvad...",Politics,410,881,54,Piden por burofax al obispo de Cartagena que r...,Piden por burofax al obispo de Cartagena que r...,pedir burofax obispo Cartagena retirar símbolo...,pedir burofax obispo retirar símbolo franquist...,pedir burofax obispo Cartagena retirar símbolo...,1,labor,1 star,0.46,5.176667,C,91042.0,Below
4,Érase una vez... (1950),Érase una vez... (1950) dirigida por Josep Esc...,Culture,114,100,9,Érase una vez... (1950) Érase una vez... (1950...,Érase una vez 1950 Érase una vez 1950 dirigida...,érar 1950 era él 1950 dirigido Josep Escobar Z...,érar 1950 1950 dirigido película entero hija c...,érar 1950 ser 1950 dirigido Josep Escobar Zipi...,0,entertainment,4 stars,0.36,3.453340,C,123376.0,Below
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123495,El juez descubre un traspaso de 150.000 euros ...,"El instructor del caso Noos, José Castro, acab...",Latest,1200,1200,46,El juez descubre un traspaso de 150.000 euros ...,El juez descubre un traspaso de 150000 euros d...,juez descubrir traspaso 150000 euros Aizóon In...,juez descubrir traspaso euros instructor caso ...,juez descubrir traspaso euros Aizóon Infanta i...,4,spanish monarchy,1 star,0.28,5.477949,B,67941.0,Below
123496,La admiración de Isaac Asimov por Carl Sagan,La historia nos ha relatado muchas historias a...,Latest,498,500,130,La admiración de Isaac Asimov por Carl Sagan L...,La admiración de Isaac Asimov por Carl Sagan L...,admiración Isaac Asimov Carl Sagan historia re...,admiración historia relatar historia admiració...,admiración Isaac Asimov Carl Sagan historia re...,0,entertainment,4 stars,0.42,5.547574,B,61846.0,Above
123497,El hombre con 59.000 libros... en su casa (ENG),"En la década de 1920, Lawrence L. Thomas, un d...",Latest,270,9400,68,El hombre con 59.000 libros... en su casa (ENG...,El hombre con 59000 libros en su casa ENG En l...,hombre 59000 libro casa ENG década 1920 Lawren...,hombre libro casa década hijo deseado nacido r...,hombre libro casa ENG década Lawrence L Thomas...,0,entertainment,5 stars,0.32,5.671209,B,50852.0,Above
123498,"La BBC habla de ""bronca por el peaje solar"" en...",La TV pública británica resalta las críticas y...,Latest,1200,2500,30,"La BBC habla de ""bronca por el peaje solar"" en...",La BBC habla de bronca por el peaje solar en E...,BBC bronca peaje solar España TV público britá...,peaje solar público británico resaltar crítica...,BBC bronca peaje solar España TV público britá...,0,entertainment,1 star,0.64,5.422632,B,72639.0,Below
123499,Multa millonaria a Tesla por exagerar autonomía,"La Comisión de Comercio Justo explicó que, seg...",Latest,405,1700,54,Multa millonaria a Tesla por exagerar autonomí...,Multa millonaria a Tesla por exagerar autonomí...,multa millonario Tesla exagerar autonomía Comi...,multa millonario exagerar autonomía mentir vel...,multa millonario Tesla exagerar autonomía Comi...,2,environment,1 star,0.69,5.312751,B,81398.0,Below

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 123500 entries, 0 to 123499
Data columns (total 19 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   title                 123500 non-null  object
 1   body                  123500 non-null  object
 2   category              123500 non-null  object
 3   votes                 123500 non-null  int64
 4   clicks                123500 non-null  int64
 5   comments              123500 non-null  int64
 6   text                  123500 non-null  object
 7   clean_text            123500 non-null  object
 8   token_lemma           123500 non-null  object
 9   noun_adj_verb         123414 non-null  object
 10  token_lemma_relevant  123500 non-null  object
 11  topic                 123500 non-null  int64
 12  topic_name            123500 non-null  object
 13  polarity              123500 non-null  object
 14  polarity_score        123500 non-null  float64
 15  score                 123500 non-null  float64
 16  score_name            123500 non-null  object
 17  rank                  123500 non-null  float64
 18  status                123500 non-null  object
dtypes: float64(3), int64(4), object(12)
memory usage: 18.8+ MB

# Clean data

In [19]:
df['polarity'] = df['polarity'].str.replace(r'\D+', '', regex=True)
df['polarity'].value_counts()

1    77808
5    16343
4    14712
2     7811
3     6826
Name: polarity, dtype: int64

In [20]:
df['polarity'] = df['polarity'].astype('int')

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 123500 entries, 0 to 123499
Data columns (total 19 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   title                 123500 non-null  object
 1   body                  123500 non-null  object
 2   category              123500 non-null  object
 3   votes                 123500 non-null  int64
 4   clicks                123500 non-null  int64
 5   comments              123500 non-null  int64
 6   text                  123500 non-null  object
 7   clean_text            123500 non-null  object
 8   token_lemma           123500 non-null  object
 9   noun_adj_verb         123414 non-null  object
 10  token_lemma_relevant  123500 non-null  object
 11  topic                 123500 non-null  int64
 12  topic_name            123500 non-null  object
 13  polarity              123500 non-null  int64
 14  polarity_score        123500 non-null  float64
 15  score                 123500 non-null  float64
 16  score_name            123500 non-null  object
 17  rank                  123500 non-null  float64
 18  status                123500 non-null  object
dtypes: float64(3), int64(5), object(11)
memory usage: 18.8+ MB

### Number of relevant

In [34]:
df['num_relevant'] = [len(df['token_lemma_relevant'][i].split()) for i in range(len(df))]

# Save file

In [36]:
df.to_csv('../DATA/news_125k-ready.csv')

In [38]:
df_tableau = df[['topic', 'topic_name', 'score', 'polarity', 'votes', 'clicks', 'comments', 'num_relevant']]

In [39]:
df_tableau

,topic,topic_name,score,polarity,votes,clicks,comments,num_relevant
0,0,entertainment,4.130580,5,144,1100,11,36
1,0,entertainment,5.459279,4,196,1800,109,21
2,1,labor,5.699596,3,330,6100,77,51
3,1,labor,5.176667,1,410,881,54,30
4,0,entertainment,3.453340,4,114,100,9,56
...,...,...,...,...,...,...,...,...
123495,4,spanish monarchy,5.477949,1,1200,1200,46,36
123496,0,entertainment,5.547574,4,498,500,130,31
123497,0,entertainment,5.671209,5,270,9400,68,44
123498,0,entertainment,5.422632,1,1200,2500,30,44
123499,2,environment,5.312751,1,405,1700,54,24

In [40]:
df_tableau.to_csv('../DATA/news_125k-tableau.csv')